use `ad-m/github-push-action`

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,28 +7,38 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+        with:
+          persist-credentials: false # [ad-m/github-push-action]: otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
+          fetch-depth: 0 # [ad-m/github-push-action]: otherwise, there would be errors pushing refs to the destination repository.
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: "2.7.5"
           bundler-cache: true
       - name: Run Rubocop (with autocorrection)
+        id: rubocop
+        continue-on-error: true
         env:
           RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
         run: bundle exec rubocop -A
       - name: Check for modified files
         id: git-check
-        if: ${{ always() }}
         run: echo "modified=$(if git diff-index --quiet HEAD --; then echo 'false'; else echo 'true'; fi)" >> $GITHUB_OUTPUT
       - name: Commit changes
         if: steps.git-check.outputs.modified == 'true'
         run: |
           git config --global user.name 'Rubocop'
-          git config --global user.email 'gary@garytou.com'
-          git remote set-url origin https://x-access-token:${{ secrets.GARYHTOU_GITHUB_PAT }}@github.com/${{ github.repository }}.git
+          git config --global user.email 'bank+github-rubocop-bot@hackclub.com'
           git commit -am "Rubocop autocorrect"
-          git push
-          exit 1 # Although a fix has been pushed, this commit with offences should still fail
+      - name: Push changes
+        if: steps.git-check.outputs.modified == 'true'
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GARYHTOU_GITHUB_PAT }}
+          branch: ${{ github.ref }}
+      - name: Fail if there were offences # Although a fix has been pushed, this commit with offences should still fail
+        if: steps.git-check.outputs.modified == 'true' || steps.rubocop.outcome == 'failure'
+        run: exit 1
   erblint:
     name: 'ERB Lint'
     runs-on: ubuntu-latest
